set userID [lindex $argv 0 ] 
set password [lindex $argv 1 ] 
set ipNumber [lindex $argv 2 ] 
set promptOnServer [lindex $argv 3]

set timeout 10
spawn  ssh $userID@$ipNumber
expect {
    "assword" {
        send "$password\n"
    }
}
sleep 2
expect $promptOnServer
send "sudo chmod -R +777 /var/lib/unifi-video/logs\n"
expect {
    "assword" {
        send "$password\n"
    }
}
sleep 1
expect $promptOnServer
send "ls -l /var/lib/unifi-video/logs\n"
sleep 1

send "exit\n"
expect eof


