set userID [lindex $argv 0 ] 
set password [lindex $argv 1 ] 
set ipNumber [lindex $argv 2 ] 

set timeout 10
if {[lindex $argv 3] == "yes"} {spawn  ssh -o StrictHostKeyChecking=no $userID@$ipNumber} else {spawn  ssh $userID@$ipNumber}

expect {
    "(yes/no" {send "yes\r"  
        expect "assword" { send "$password\n"} 
    }
    "assword"    {  send "$password\r"
        expect {
            ":"     { send "exit\r" 
                    }
            "refused"     {  exit 1  }
             "denied"     {  exit 2  }   
        }
    }
}
expect eof