set userID [lindex $argv 0 ] 
set password [lindex $argv 1 ] 
set ipNumber [lindex $argv 2 ] 
set promptOnServer [lindex $argv 3]

set timeout 20
spawn  ssh $userID@$ipNumber
expect {
    "(yes/no" {
        send "yes\n"
        sleep 0.1
        expect "assword" { send "$password\n"}
    }
    "assword: " {
        send "$password\n"
    }
}

set timeout 3
sleep 3
expect "$promptOnServer" {send "sensors -u\r"}
sleep 2
expect "$promptOnServer"
sleep 1
send "exit\r"
sleep 0.1
expect eof
